# Generated by Django 6.0.3 on 2026-03-31 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('reward_score', models.IntegerField(default=0, verbose_name='积分奖励')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待接取'), ('in_progress', '已接取'), ('completed', '已完成'), ('cancelled', '已撤销')], default='pending', max_length=20, verbose_name='状态')),
                ('is_draft', models.BooleanField(default=False, verbose_name='是否草稿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('acceptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_missions', to=settings.AUTH_USER_MODEL, verbose_name='接取人')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_missions', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '委托',
                'verbose_name_plural': '委托',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='missions/%Y%m%d/', verbose_name='图片')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='missions.mission', verbose_name='委托')),
            ],
            options={
                'verbose_name': '委托图片',
                'verbose_name_plural': '委托图片',
            },
        ),
    ]
